// Code generated by mockery v1.0.0. DO NOT EDIT.

package writers

import (
	s3manager "github.com/aws/aws-sdk-go/service/s3/s3manager"
	mock "github.com/stretchr/testify/mock"
)

// MockS3Uploader is an autogenerated mock type for the S3Uploader type
type MockS3Uploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: input, options
func (_m *MockS3Uploader) Upload(input *s3manager.UploadInput, options ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *s3manager.UploadOutput
	if rf, ok := ret.Get(0).(func(*s3manager.UploadInput, ...func(*s3manager.Uploader)) *s3manager.UploadOutput); ok {
		r0 = rf(input, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3manager.UploadOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*s3manager.UploadInput, ...func(*s3manager.Uploader)) error); ok {
		r1 = rf(input, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
